In [ ]:
#numpy --> eg ludo game (creating random numbers from (1 to 6) by using numpy random function)

In [ ]:
#FUNCTIONS | Built-in Methods

#arange   --> if you need a number in some range
#zeros    --> if you need the numbers in ZEROS 
#ones     --> if you need the numbers in ones
#linspace --> it will generate a number in seperate interval of time
#eye      --> it will create a identity matrix by using eye
#Random   --> rand / randn / randint   (random is used to create a random numbers)
#random.rand ---> create a random numbers by giving range eg: np.random.rand(4) / matrix number eg: np.radom.rand(5,5) (eg : ludo)
#random.randn --> create a numbers by using standard normal distribution
#random.rantint --> random numbers from low(inclusive) and high(exclusive)
#reshape
#max,min,argmax,argmin (max and min --> provides maximum and minimum num)
#argmax,argmin --> this will give the index number
#indexing and selection
#Broadcasting (normally broadcasting features will not be there in  the list, but we have oin numpy thats one advantage)

#Broadcast - means setting the value with index range
#copy()  --> to copy some data in array (to avoid slicing issues) -->check the example in below code

#Arithmetic Function
---------------------

#np.sqrt() --> square root
#np.exp() -->  calculating exponential (e^)

#Practices
----------

#create an array of 10 zeros & ones
#create an array of 10 fives
#create an array of the integers from 10 to 50
#create an array of all even numbers from 10 to 50
#create a 3x3 matrics with value range 0 to 8.
#create a 3x3 identity matrix
#generate a random numbers between 0 & 1
#generate 25 random numbers from a std(standard normal distribution)
#create a array 20 line spaced points b/w 0 & 1

#Note : in numpy we have a function called (ndarray)  ---> which is 5o times faster than list, also numpy arrays are stored in continuous place in memory but list doesnt






In [1]:
#arange

import numpy as np

a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#zeros and ones

b = np.zeros(3)
b


array([0., 0., 0.])

In [8]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [10]:

c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#linspace

a = np.linspace(1,10,3)
a

#(number will generate from 1 to 10 , space will split of 3)

array([ 1. ,  5.5, 10. ])

In [4]:
#eye

a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#random
#random.rand
#random.randn
#random.randint

a = np.random.rand(4)
a

array([0.8298809 , 0.37409464, 0.57586652, 0.45559833])

In [16]:
a = np.random.rand(5,5)
a

array([[0.06122407, 0.99324688, 0.17183739, 0.64207737, 0.49350037],
       [0.55896586, 0.5968891 , 0.95638231, 0.19606308, 0.14993493],
       [0.49211592, 0.32872539, 0.76314022, 0.20018152, 0.00988852],
       [0.67685309, 0.09789209, 0.60880188, 0.5624162 , 0.1079484 ],
       [0.8791438 , 0.51659276, 0.69780672, 0.66643003, 0.65505717]])

In [17]:
b = np.random.randn(4)
b

array([-1.52728302, -0.69645998,  0.39009194,  0.54883217])

In [19]:
b = np.random.randn(5,5)
b

array([[ 0.31483805, -0.59689246, -1.59709101,  1.19025168,  0.95917377],
       [-0.06629584, -0.76650278, -0.56964985, -0.71059851,  0.3056429 ],
       [ 0.51841269, -1.18196368,  1.4197658 , -0.18839865,  0.97469065],
       [ 2.40127599, -0.58524418, -0.08205151,  0.00727574, -0.16332486],
       [-2.55555269, -1.22658167, -2.41653874,  0.53748033, -0.92334218]])

In [6]:
#randint --> see the below example 

c = np.random.randint(1,7)
c

3

In [21]:
c = np.random.randint(1,6,10)   #i want numbers 1 to 6 , but need 10 times
c

array([2, 3, 1, 3, 2, 5, 2, 2, 5, 3])

In [11]:
#Array attributes and methods

a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
an = np.random.randint(0,50,10)
an

array([41, 39, 30, 37, 43, 43,  5, 26, 24,  7])

In [12]:
d = a.reshape(5,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
#max,min,argmax,argmin
a = np.array([1,3,4,2,6,7,8,4,5])
print(a)
b = np.max(a)
c = np.min(a)
d = np.argmax(a)
e = np.argmin(a)

print(b)
print(c)
print(d)
print(e)

[1 3 4 2 6 7 8 4 5]
8
1
6
0


In [17]:
#broadcasting
a = np.arange(10)
print(a)

a[0:4] = 1000
a

[0 1 2 3 4 5 6 7 8 9]


array([1000, 1000, 1000, 1000,    4,    5,    6,    7,    8,    9])

In [52]:
# slicing --> problem example

a = np.arange(10)
print(a)

s = a[0:4]     # here i need 0 to 4 index values and saving that to "s"
print(s)

s[:] = 777       # here i am going to replace with "777" number in "S"
print(s)

print(a)      # but when i check in main array, this is also changes , hence to overcome this we are using "copy()" method, which does not affect main array

#copy()



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[777 777 777 777]
[777 777 777 777   4   5   6   7   8   9]


In [56]:
#copy()

a = np.arange(10)
print(a)

s = a[0:4].copy()
print(s)

s[:] = 333
print(s)

print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[333 333 333 333]
[0 1 2 3 4 5 6 7 8 9]


In [57]:
#Arithmetic operation 

#can't be performed these in LIST so easily
#but you can do it in NUMPY easily

c = np.arange(0,11)
print(c)

print(c*c)      #it will work
print(c+c)      #it will work
print(c/c)      #output will come but this will throw error / wraning as the data has "0" values , anything/0 = infininity (so it will give error)
print(c ** 3)   #o/p will come , but this will throw error / wraning as the data has "0" values , anything/0 = infininity (so it will give error)


[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   4   9  16  25  36  49  64  81 100]
[ 0  2  4  6  8 10 12 14 16 18 20]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[   0    1    8   27   64  125  216  343  512  729 1000]


C:\Users\Athiban\AppData\Local\Temp/ipykernel_20472/1627726123.py:11: RuntimeWarning: invalid value encountered in true_divide
  print(c/c)


In [58]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [59]:
np.exp(c)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [60]:
#practice

#create an array of 10 zeros and ones

p = np.zeros(10)
print(p)

p_1 = np.ones(10)
print(p_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
#create an array of 10 fives

p = np.ones(10) * 5
p

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [62]:
#create an array of the integers 10 to 50

p = np.arange(10,51)
p

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [63]:
#create an array of all even integers 10 to 50

p = np.arange(10,51,2)
p

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [64]:
#create a 3x3 matrix with he value range 0 to 8

p = np.arange(9).reshape(3,3)
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
#create a 3x3 identity matrix

p = np.eye(3)
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
#generate a random numbers  0 to 1

p = np.random.rand(1)
p

array([0.82534754])

In [69]:
#generate 25 numbers from standard deviation distribution

p = np.random.randn(25)
p

array([-1.76660464, -0.94561129,  1.91893163, -2.09663978,  0.41537184,
        0.63181957, -0.36152677,  0.54773371, -0.55302511, -0.57015131,
        0.55475473, -0.13418215, -0.30834223, -2.42074183, -0.36399274,
        0.29148803,  0.93495391,  0.82542546,  0.80505183, -0.68431988,
       -0.60460316, -0.83413838, -0.50374447,  1.35760437,  0.90306922])

In [70]:
#create an array 20 line spaced points b/w 0 & 1

p = np.linspace(0,1,20)
p

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])