In [ ]:
#Numpy --> Numerical python
#is a python package / library
#to perform Mathematical operation
#it can handle numbers and maths 

# numpy is used for 3D array and n-dimensional array

#important:
#doing mathematical operation for array --> you can use numpy (we can perform array related operation)

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#example for normal calculation vs numpy calculation 

list1 = [1,2,3,4]
list2 = [1,2,3,4]
list3 = list1 * list2  #you cant do these kind of operations in normal coding eg:python (list) (only you can do + --> is called concatenation)
list3

TypeError: can't multiply sequence by non-int of type 'list'

In [1]:
a = [1,2,3,4,5,6,7,8..................................10000]
b = 2
c = a +b
d = a -b
e = a/b
f = a % b
print(c)
print(d)
print(e)
print(f)

3
-1
0.5
1


In [5]:
#example for concatenation 2 lists

list1 = [1,2,3,4]
list2 = [1,2,3,4]
list3 = list1 + list2  
list3

[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
#example for numpy
#np.array -->is a built-in function
import numpy as np

nump1 = np.array([1,2,3,4])
nump2 = np.array([1,2,3,4])

nump3 = nump1 * nump2
nump3


array([ 1,  4,  9, 16])

In [3]:
#example for numpy
import numpy as np

nump1 = np.array([1,2,3,4])
nump2 = np.array([1,2,3,4])

nump3 = nump1 + nump2
nump3

array([2, 4, 6, 8])

In [ ]:
# array Creation

#if you are doing array in numpy you can do any type of array --> wh means single Dimension (1D)/2D/3D .... n-dimensional array

types of array

1D --> one/single dimension [1,2]  / [1,2,3] / [1,2,3,4,...................1000]
2D --> two dimension (2 x 2 matrix)
[1,2]
[2,3]
3D --> three dimension (3 x 3 matrix)

[1,2,3]
[2,3,4]
[4,5,6]


In [9]:
a = np.array([1,2])#single dimension
a

array([1, 2])

In [5]:
a.ndim    #ndim --> will tell you what type of dimension it is

1

In [10]:
a.dtype

dtype('int32')

In [12]:
a.shape

(2,)

In [13]:
a.size

2

In [18]:
b1 = np.array([
    [1,2],
    [2,3]
    
])
b1

array([[1, 2],
       [2, 3]])

In [16]:
b = np.array([[1,2],[2,4]])
b

array([[1, 2],
       [2, 4]])

In [36]:
b.ndim

2

In [50]:
b.shape #2rows and 2 columns in pandas but in numpy its an array so it is two cross two (2 * 2)

(2, 2)

In [49]:
b.size

4

In [17]:
#if you want to reshape this, use reshape

b.reshape(4,1)  #4 means rows and 1 is a columns


array([[1],
       [2],
       [2],
       [4]])

In [53]:
b.dtype

dtype('int32')

In [56]:
#if you want to change the data type

b = np.array([[1,2],[2,4]],dtype = 'float64')
b.dtype

dtype('float64')

In [30]:
c = np.array([
    [1,2],
    [2,3],
    [4,5]
    
])
c

array([[1, 2],
       [2, 3],
       [4, 5]])

In [31]:
c.ndim

2

In [26]:
c = np.array([
    [1.6,2,3,4,5,6,7],
    [6,7,8,9,2,3.4,4],
    [3,4,5,6,8,9,1.2]
    
]) #it will show 2dim only , bcoz you need to give 3 [[ ]], if you want 3d
c

array([[1.6, 2. , 3. , 4. , 5. , 6. , 7. ],
       [6. , 7. , 8. , 9. , 2. , 3.4, 4. ],
       [3. , 4. , 5. , 6. , 8. , 9. , 1.2]])

In [29]:
c.ndim

2

In [28]:
c.dtype

dtype('float64')

In [32]:
d = np.array(
    [[
        [1,2],
        [2,4],
        [4,8]
    ]]) 
d

array([[[1, 2],
        [2, 4],
        [4, 8]]])

In [33]:
d.ndim

3

In [34]:
d.shape

(1, 3, 2)

In [45]:
d.size

6

In [34]:
e = np.array(
    [[
        [4,2,5],
        [2,4,6],
        [4,8,7]
    ]] ) 
e

array([[[4, 2, 5],
        [2, 4, 6],
        [4, 8, 7]]])

In [35]:
e.ndim

3

In [36]:
e.shape

(1, 3, 3)

In [44]:
e.size

9

In [46]:
f = np.array(
    [[[
        [1,2,5],
        [2,4,6],
        [4,8,7],
        [1,2,3]
    ]]]) 
f

array([[[[1, 2, 5],
         [2, 4, 6],
         [4, 8, 7],
         [1, 2, 3]]]])

In [111]:
f.ndim

4

In [46]:
a1 = np.array([9,4,16,20,50,60,70])
a1

array([ 9,  4, 16, 20, 50, 60, 70])

In [43]:
a1.ndim

1

In [40]:
a1.max() #simple operation can perform this way, but when you trying like sqrt operations and all it will throe error --> check next cell


70

In [47]:
np.sqrt(a1)

#9 = 3x3 =9
#16 = 4x4 = 16

array([3.        , 2.        , 4.        , 4.47213595, 7.07106781,
       7.74596669, 8.36660027])

In [62]:
a1.sqrt()  #not a correct syntax


AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [48]:
a = np.max(a1)
b = np.min(a1)
c = np.sum(a1)
print(a)
print(b)
print(c)

70
4
229


In [67]:
np.sqrt(a1)

array([3.16227766, 6.32455532, 5.47722558, 4.47213595, 7.07106781,
       7.74596669, 8.36660027])

In [3]:
#Maths 

l = np.array([[2,3,4],[4,5,6]])
l

array([[2, 3, 4],
       [4, 5, 6]])

In [4]:
l.ndim

2

In [5]:
l = np.array([[2,3,4],[4,5,6]],dtype = 'complex')
l

array([[2.+0.j, 3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [71]:
l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
l = np.zeros((3,3))
l

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
l = np.zeros((2,2))
l

array([[0., 0.],
       [0., 0.]])

In [77]:
l = np.ones((3,3))
l

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
l = np.linspace(1,5,7)
l

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [9]:
l = np.indices((3,3))
l

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [86]:
l = np.indices((4,3))
l

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [87]:
#Indexing and Slicing

#indexing --> will do backword also (using -)
#example 1 - single dimensional array

l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
l[1]

1

In [91]:
l[-1]

9

In [92]:
l[-9]

1

In [16]:
#emaple2 - multi dimensional array

l2 = np.array([[5,6,7],[2,3,4]])
l2

array([[5, 6, 7],
       [2, 3, 4]])

In [17]:
l2.ndim

2

## so here 1st position will be the zero'th position means --> [1,2,3] , 2nd position will be the first position --> [2,3,4]

[1,2,3]  ---> 0[0] = 1 , 0[1] = 2, 0[2] = 3
[2,3,4]  ---> 1[0] = 2, 1[1] = 3 , 1[2] = 4



In [18]:
l2[0]

array([5, 6, 7])

In [19]:
l2[1]

array([2, 3, 4])

In [23]:
l2[0][0]

5

In [22]:
l2[1][2]

4

## Slicing --> means setting up the RANGE ( need from some value to some value called as slicing)

In [24]:
l3 = np.array([0,1,2,3,4,5,6,7,8,9])
l3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
l3[2:6]

array([2, 3, 4, 5])

In [26]:
l3[3:8:2] #starts from 3rd postion to (8-1) position , by implementing 2 steps, so it will skip the 4 and 6 (take the coming 2nd position)


array([3, 5, 7])

In [103]:
l3[3:8:4]

array([3, 7])

In [105]:
#Slice --> there is a function called slice

s = slice(3,8,4)
l3[s]

array([3, 7])

In [106]:
l3[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [107]:
l3[:3]

array([0, 1, 2])

In [27]:
l4 = np.array([[1,2],[2,3],[3,4]])
l4

array([[1, 2],
       [2, 3],
       [3, 4]])

In [29]:
l4[1:3]

array([[2, 3],
       [3, 4]])

In [ ]:
#complete practice


In [113]:
s = np.array([1,2,3,4])
s

array([1, 2, 3, 4])

In [114]:
s.ndim

1

In [115]:
s = np.array([1,2,3,4],ndmin = 2)
s

array([[1, 2, 3, 4]])

In [117]:
s.ndim

2

In [118]:
s = np.array([1,2,3,4],ndmin = 3)
s

array([[[1, 2, 3, 4]]])

In [34]:
#creating a array by using an existing array

ofc_mate = np.array([1,2,3,4,5,7,8,9])
print(ofc_mate)
abc = np.asarray(ofc_mate)
abc

[1 2 3 4 5 7 8 9]


In [35]:
abc = np.asarray(ofc_mate)
abc

array([1, 2, 3, 4, 5, 7, 8, 9])

In [120]:
x = np.arange(1,50,10 , dtype = 'int32')
x

array([ 1, 11, 21, 31, 41])